# request constants
SERVER_URL = "http://192.168.50.100:5000"
CONNECT_TIMEOUT = 1
READ_TIMEOUT = 1
# button constants
START_BUTTON_PIN_IN = 8
START_LED_PIN_OUT = 10
RESET_BUTTON_PIN_IN = 16
RESET_LED_PIN_OUT = 18
# RFID reader constants
PLAYER_1_RFID_SS_PIN = 0
PLAYER_2_RFID_SS_PIN = 1
