# request constants
SERVER_URL = "http://Lifc2025PropsServer.local"
CONNECT_TIMEOUT = 1
READ_TIMEOUT = 4
# button constants
START_BUTTON_PIN_IN = 15
START_LED_PIN_OUT = 13
RESET_BUTTON_PIN_IN = 16
RESET_LED_PIN_OUT = 18
# buzzer constants
BUZZER_LEFT_PIN_OUT = 31
BUZZER_RIGHT_PIN_OUT = 32
# RFID reader constants
PLAYER_1_RFID_SS_PIN = 1
PLAYER_2_RFID_SS_PIN = 0

