# request constants
SERVER_URL = "http://192.168.50.100:5000"
CONNECT_TIMEOUT = 1
READ_TIMEOUT = 1
# button constants
START_BUTTON_PIN_IN = 16
START_LED_PIN_OUT = 18
RESET_BUTTON_PIN_IN = 15
RESET_LED_PIN_OUT = 13
# buzzer constants
BUZZER_LEFT_PIN_OUT = 31
BUZZER_RIGHT_PIN_OUT = 32
# RFID reader constants
PLAYER_1_RFID_SS_PIN = 0
PLAYER_2_RFID_SS_PIN = 1

