#!/bin/bash
# enable static IP on LifcArcadePropsInput

# Set the IP address of eth0 to 192.168.50.101/24
# ip addr add 192.168.50.101/24 dev eth0
# NOTE: this step is already setup in dietpi-config

# Enable the eth0 interface
# ip link set dev eth0 up
# NOTE: this step is already setup in dietpi-config

# Remove the default route from eth0
ip route del default dev eth0

# Enable the wlan0 interface
# ip link set dev wlan0 up
# NOTE: this step is already setup in dietpi-config

# Set the default route to 192.168.1.1 on wlan0
# or to 192.168.10.1 in my home network
ip route add default via 192.168.10.1 dev wlan0

exit 0