#!/bin/bash
# startup scripts to listen to various inputs

# listen to inputs from start button in BG
/home/trigger/lifc-arcade-props/inputs/start_button.py &

# listen to inputs from reset button in BG
/home/trigger/lifc-arcade-props/inputs/reset_button.py &

# listen to inputs from player 1 RFID reader in BG
/home/trigger/lifc-arcade-props/inputs/player_1_rfid.py &

# listen to inputs from player 2 RFID reader in BG
/home/trigger/lifc-arcade-props/inputs/player_2_rfid.py &

exit 0