#!/bin/bash

mkdir -p /var/log/nginx /var/log/gunicorn /var/log/redis
touch /var/log/nginx/access.log /var/log/nginx/error.log \
          /var/log/gunicorn/access.log /var/log/gunicorn/error.log \
          /var/log/redis/redis-server.log