#!/home/server/lifc-arcade-props/server/.venv/bin/python
# startup script for the server

gunicorn -w 4 'main:application' --chdir=/home/server/lifc-arcade-props --preload -b 192.168.50.100:5000 --daemon

exit 0